# Generated by Django 5.0.4 on 2024-05-09 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='size',
        ),
        migrations.AddField(
            model_name='productitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size'),
        ),
    ]
