# Generated by Django 5.0.4 on 2024-05-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productitem_color_remove_productitem_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20),
        ),
    ]
