# Generated by Django 5.0.4 on 2024-05-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_paymentmethod_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_cvc',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_number',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(max_length=10),
        ),
    ]
